<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <Version>1.1.1</Version>
    <Product>Pulsar</Product>
    <Copyright>© 2025 SpaceGT</Copyright>
  </PropertyGroup>
  <PropertyGroup>
    <AssemblyName>Updater</AssemblyName>
    <RootNamespace>Pulsar.Updater</RootNamespace>
  </PropertyGroup>
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net48</TargetFramework>
    <UseWindowsForms>true</UseWindowsForms>
    <Nullable>enable</Nullable>
    <LangVersion>latest</LangVersion>
    <AutoGenerateBindingRedirects>false</AutoGenerateBindingRedirects>
  </PropertyGroup>
  <PropertyGroup>
    <PlatformTarget>x64</PlatformTarget>
  </PropertyGroup>
  <PropertyGroup>
    <ApplicationIcon>../Interface/Assets/icon.ico</ApplicationIcon>
  </PropertyGroup>
  <PropertyGroup>
    <StartAction>Program</StartAction>
    <StartWorkingDirectory>$(Pulsar)</StartWorkingDirectory>
    <StartProgram>$(Pulsar)/Updater.exe</StartProgram>
  </PropertyGroup>
  <Target Name="Deploy" AfterTargets="Build" Condition="'$(TargetPlatform)' == 'Windows'">
    <PropertyGroup>
      <LicensePath>$(MSBuildProjectDirectory)/../LICENSE</LicensePath>
      <ReadmePath>$(MSBuildProjectDirectory)/../README.md</ReadmePath>
    </PropertyGroup>
    <ItemGroup>
      <DeployFile Include="$(TargetPath)" />
    </ItemGroup>
    <Error Condition="!Exists('$(LicensePath)')" Text="License file not found!" />
    <Error Condition="!Exists('$(ReadmePath)')" Text="Readme file not found!" />
    <Copy SourceFiles="@(DeployFile)" DestinationFolder="$(Pulsar)" />
    <Copy SourceFiles="$(LicensePath)" DestinationFolder="$(Pulsar)" />
    <Copy SourceFiles="$(ReadmePath)" DestinationFolder="$(Pulsar)" />
  </Target>
  <Target Name="Verify" BeforeTargets="PrepareForBuild">
    <Error Condition="'$(Pulsar)' == ''" Text="Specify Pulsar's deployment location!" />
    <Error Condition="$(Pulsar.Contains(';'))" Text="Pulsar directory is not unique!" />
  </Target>
  <ItemGroup>
    <Reference Include="System.IO.Compression" />
  </ItemGroup>
</Project>
