<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <Version>1.0.0</Version>
    <Product>Pulsar</Product>
    <Copyright>© 2026 SpaceGT</Copyright>
  </PropertyGroup>
  <PropertyGroup>
    <AssemblyName>Interface</AssemblyName>
    <RootNamespace>Pulsar.Interface</RootNamespace>
  </PropertyGroup>
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net48</TargetFramework>
    <Nullable>disable</Nullable>
    <LangVersion>latest</LangVersion>
  </PropertyGroup>
  <PropertyGroup>
    <Platforms>x64</Platforms>
    <PlatformTarget>x64</PlatformTarget>
    <Configurations>Debug;Release</Configurations>
  </PropertyGroup>
  <PropertyGroup Condition="'$(Configuration)|$(Platform)' == 'Debug|x64'">
    <DebugSymbols>true</DebugSymbols>
    <OutputPath>bin/Debug/</OutputPath>
    <DefineConstants>DEBUG;TRACE</DefineConstants>
    <DebugType>full</DebugType>
    <LangVersion>latest</LangVersion>
    <ErrorReport>prompt</ErrorReport>
  </PropertyGroup>
  <PropertyGroup Condition="'$(Configuration)|$(Platform)' == 'Release|x64'">
    <OutputPath>bin/Release/</OutputPath>
    <DefineConstants>TRACE</DefineConstants>
    <Optimize>true</Optimize>
    <DebugType>pdbonly</DebugType>
    <LangVersion>latest</LangVersion>
    <ErrorReport>prompt</ErrorReport>
  </PropertyGroup>
  <PropertyGroup>
    <ApplicationIcon>Assets/icon.ico</ApplicationIcon>
    <ApplicationManifest>app.manifest</ApplicationManifest>
    <AvaloniaUseCompiledBindingsByDefault>true</AvaloniaUseCompiledBindingsByDefault>
  </PropertyGroup>
  <Target Name="Deploy" AfterTargets="Build">
    <PropertyGroup>
      <DeployDirectory>$(Pulsar)/Libraries/Interface</DeployDirectory>
      <LicensePath>$(MSBuildProjectDirectory)/../LICENSE</LicensePath>
    </PropertyGroup>
    <ItemGroup>
      <DeployFile Include="$(TargetPath)" />
      <DeployFile Include="$(TargetPath).config" />
      <DeployFile Include="$(TargetDir)Pulsar.Protocol.dll" />
      <DeployFile Include="$(TargetDir)Newtonsoft.Json.dll" />
      <DeployFile Include="$(TargetDir)MicroCom.Runtime.dll" />
      <DeployFile Include="$(TargetDir)HarfBuzzSharp.dll" />
      <DeployFile Include="$(TargetDir)x64/libHarfBuzzSharp.dll" />
      <DeployFile Include="$(TargetDir)SkiaSharp.dll" />
      <DeployFile Include="$(TargetDir)x64/libSkiaSharp.dll" />
      <DeployFile Include="$(TargetDir)av_libglesv2.dll" />
      <DeployFile Include="$(TargetDir)Microsoft.Bcl.AsyncInterfaces.dll" />
      <DeployFile Include="$(TargetDir)AnimatedImage.dll" />
      <DeployFile Include="$(TargetDir)AnimatedImage.Avalonia.dll" />
      <DeployFile Include="$(TargetDir)Avalonia.dll" />
      <DeployFile Include="$(TargetDir)Avalonia.Base.dll" />
      <DeployFile Include="$(TargetDir)Avalonia.Controls.dll" />
      <DeployFile Include="$(TargetDir)Avalonia.Dialogs.dll" />
      <DeployFile Include="$(TargetDir)Avalonia.Markup.dll" />
      <DeployFile Include="$(TargetDir)Avalonia.Markup.Xaml.dll" />
      <DeployFile Include="$(TargetDir)Avalonia.MicroCom.dll" />
      <DeployFile Include="$(TargetDir)Avalonia.OpenGL.dll" />
      <DeployFile Include="$(TargetDir)Avalonia.Remote.Protocol.dll" />
      <DeployFile Include="$(TargetDir)Avalonia.Skia.dll" />
      <DeployFile Include="$(TargetDir)Avalonia.Themes.Fluent.dll" />
      <DeployFile Include="$(TargetDir)Avalonia.Win32.dll" />
      <DeployFile Include="$(TargetDir)Avalonia.Metal.dll" />
      <DeployFile Include="$(TargetDir)System.Buffers.dll" />
      <DeployFile Include="$(TargetDir)System.Memory.dll" />
      <DeployFile Include="$(TargetDir)System.ValueTuple.dll" />
      <DeployFile Include="$(TargetDir)System.ComponentModel.Annotations.dll" />
      <DeployFile Include="$(TargetDir)System.Numerics.Vectors.dll" />
      <DeployFile Include="$(TargetDir)System.Runtime.CompilerServices.Unsafe.dll" />
      <DeployFile Include="$(TargetDir)System.Threading.Tasks.Extensions.dll" />
    </ItemGroup>
    <Error Condition="!Exists('$(LicensePath)')" Text="License file not found!" />
    <RemoveDir Directories="$(DeployDirectory)" />
    <Copy SourceFiles="@(DeployFile)" DestinationFolder="$(DeployDirectory)" />
    <Copy SourceFiles="$(LicensePath)" DestinationFolder="$(Pulsar)" />
  </Target>
  <Target Name="Verify" BeforeTargets="PrepareForBuild">
    <Error Condition="'$(Pulsar)' == ''" Text="Specify Pulsar's deployment location!" />
    <Error Condition="$(Pulsar.Contains(';'))" Text="Pulsar directory is not unique!" />
  </Target>
  <ItemGroup>
    <ProjectReference Include="../Protocol/Protocol.csproj" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="Avalonia.Win32" Version="11.0.10" />
    <PackageReference Include="Avalonia.Skia" Version="11.0.10" />
    <PackageReference Include="Avalonia.Themes.Fluent" Version="11.0.10" />
    <PackageReference Include="AnimatedImage.Avalonia" Version="2.1.4" />
  </ItemGroup>
  <ItemGroup>
    <AvaloniaResource Include="Assets\**" />
  </ItemGroup>
</Project>
