<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <Version>2.3.1</Version>
    <Product>Pulsar</Product>
    <Copyright>© 2026 SpaceGT</Copyright>
    <AssemblyTitle>Pulsar</AssemblyTitle>
    <Description>Plugin and Mod loader for Space Engineers 1</Description>
  </PropertyGroup>
  <PropertyGroup>
    <RootNamespace>Pulsar.Legacy</RootNamespace>
    <PackageId>Pulsar</PackageId>
    <IsPackable>false</IsPackable>
  </PropertyGroup>
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFrameworks>net48;net10.0-windows</TargetFrameworks>
    <Nullable>disable</Nullable>
    <LangVersion>latest</LangVersion>
  </PropertyGroup>
  <PropertyGroup Condition="'$(TargetFramework)' == 'net48'">
    <AssemblyName>Legacy</AssemblyName>
    <StartProgram>$(Pulsar)/Legacy.exe</StartProgram>
  </PropertyGroup>
  <PropertyGroup Condition="'$(TargetFramework)' != 'net48'">
    <AssemblyName>Interim</AssemblyName>
    <StartProgram>$(Pulsar)/Interim.exe</StartProgram>
  </PropertyGroup>
  <PropertyGroup>
    <Platforms>x64</Platforms>
    <PlatformTarget>x64</PlatformTarget>
    <Configurations>Debug;Release</Configurations>
  </PropertyGroup>
  <PropertyGroup Condition="'$(Configuration)|$(Platform)' == 'Debug|x64'">
    <DebugSymbols>true</DebugSymbols>
    <OutputPath>bin/Debug/</OutputPath>
    <DefineConstants>DEBUG;TRACE</DefineConstants>
    <DebugType>full</DebugType>
    <LangVersion>latest</LangVersion>
    <ErrorReport>prompt</ErrorReport>
  </PropertyGroup>
  <PropertyGroup Condition="'$(Configuration)|$(Platform)' == 'Release|x64'">
    <OutputPath>bin/Release/</OutputPath>
    <DefineConstants>TRACE</DefineConstants>
    <Optimize>true</Optimize>
    <DebugType>pdbonly</DebugType>
    <LangVersion>latest</LangVersion>
    <ErrorReport>prompt</ErrorReport>
  </PropertyGroup>
  <PropertyGroup>
    <ApplicationIcon>../Interface/Assets/icon.ico</ApplicationIcon>
  </PropertyGroup>
  <PropertyGroup>
    <ApplicationManifest>app.manifest</ApplicationManifest>
  </PropertyGroup>
  <PropertyGroup>
    <!-- Required by SpaceEngineers internally; Deserialization is patched to use safer methods. -->
    <EnableUnsafeBinaryFormatterSerialization>true</EnableUnsafeBinaryFormatterSerialization>
  </PropertyGroup>
  <PropertyGroup>
    <StartAction>Program</StartAction>
    <StartWorkingDirectory>$(Pulsar)</StartWorkingDirectory>
  </PropertyGroup>
  <Target Name="Deploy" AfterTargets="Build">
    <PropertyGroup>
      <DeployDirectory>$(Pulsar)/Libraries/$(AssemblyName)</DeployDirectory>
      <LicensePath>$(MSBuildProjectDirectory)/../LICENSE</LicensePath>
    </PropertyGroup>
    <ItemGroup>
      <DeployRootFile Include="$(TargetDir)$(AssemblyName).exe" />
      <DeployRootFile Include="$(TargetDir)$(AssemblyName).exe.config" Condition="'$(TargetFrameworkIdentifier)' == '.NETFramework'" />
      <DeployRootFile Include="$(TargetDir)$(AssemblyName).dll" Condition="'$(TargetFrameworkIdentifier)' == '.NETCoreApp'" />
      <DeployRootFile Include="$(TargetDir)$(AssemblyName).runtimeconfig.json" Condition="'$(TargetFrameworkIdentifier)' == '.NETCoreApp'" />
      <DeployRootFile Include="$(TargetDir)$(AssemblyName).deps.json" Condition="'$(TargetFrameworkIdentifier)' == '.NETCoreApp'" />
      <DeployLibraryFile Include="$(TargetDir)Pulsar.Shared.dll" />
      <DeployLibraryFile Include="$(TargetDir)Pulsar.Protocol.dll" />
      <DeployLibraryFile Include="$(TargetDir)0Harmony.dll" />
      <DeployLibraryFile Include="$(TargetDir)Mono.Cecil.dll" />
      <DeployLibraryFile Include="$(TargetDir)Microsoft.Win32.Registry.dll" Condition="'$(TargetFrameworkIdentifier)' == '.NETFramework'" />
      <DeployLibraryFile Include="$(TargetDir)Newtonsoft.Json.dll" />
      <DeployLibraryFile Include="$(TargetDir)Gameloop.Vdf.dll" />
      <DeployLibraryFile Include="$(TargetDir)NLog.dll" />
      <DeployLibraryFile Include="$(TargetDir)protobuf-net.dll" />
      <DeployLibraryFile Include="$(TargetDir)FuzzySharp.dll" />
      <DeployLibraryFile Include="$(TargetDir)NuGet.*.dll" />
    </ItemGroup>
    <Error Condition="!Exists('$(LicensePath)')" Text="License file not found!" />
    <RemoveDir Directories="$(DeployDirectory)" />
    <Copy SourceFiles="@(DeployRootFile)" DestinationFolder="$(Pulsar)" />
    <Copy SourceFiles="@(DeployLibraryFile)" DestinationFolder="$(DeployDirectory)" />
    <Copy SourceFiles="$(LicensePath)" DestinationFolder="$(Pulsar)" />
  </Target>
  <Target Name="Verify" BeforeTargets="PrepareForBuild">
    <Error Condition="'$(Pulsar)' == ''" Text="Specify Pulsar's deployment location!" />
    <Error Condition="$(Pulsar.Contains(';'))" Text="Pulsar directory is not unique!" />
    <Error Condition="'$(Bin64)' == '' or !Exists('$(Bin64)')" Text="Specify SpaceEngineers Bin64 path!" />
  </Target>
  <ItemGroup>
    <ProjectReference Include="../Shared/Shared.csproj" />
  </ItemGroup>
  <ItemGroup Condition="'$(TargetFramework)' == 'net10.0-windows'">
    <!-- Required by SpaceEngineers internally; Pulsar uses Avalonia rather then WinForms. -->
    <FrameworkReference Include="Microsoft.WindowsDesktop.App" />
  </ItemGroup>
  <ItemGroup>
    <Reference Include="Microsoft.CodeAnalysis" HintPath="$(Bin64)\Microsoft.CodeAnalysis.dll" Private="False" />
    <Reference Include="Sandbox.Game" HintPath="$(Bin64)\Sandbox.Game.dll" Private="False" />
    <Reference Include="Sandbox.Graphics" HintPath="$(Bin64)\Sandbox.Graphics.dll" Private="False" />
    <Reference Include="SpaceEngineers" HintPath="$(Bin64)\SpaceEngineers.exe" Private="False" />
    <Reference Include="SpaceEngineers.Game" HintPath="$(Bin64)\SpaceEngineers.Game.dll" Private="False" />
    <Reference Include="VRage" HintPath="$(Bin64)\VRage.dll" Private="False" />
    <Reference Include="VRage.Game" HintPath="$(Bin64)\VRage.Game.dll" Private="False" />
    <Reference Include="VRage.Input" HintPath="$(Bin64)\VRage.Input.dll" Private="False" />
    <Reference Include="VRage.Library" HintPath="$(Bin64)\VRage.Library.dll" Private="False" />
    <Reference Include="VRage.Math" HintPath="$(Bin64)\VRage.Math.dll" Private="False" />
    <Reference Include="VRage.Platform.Windows" HintPath="$(Bin64)\VRage.Platform.Windows.dll" Private="False" />
    <Reference Include="VRage.Scripting" HintPath="$(Bin64)\VRage.Scripting.dll" Private="False" />
  </ItemGroup>
  <ItemGroup Condition="'$(TargetFramework)' == 'net48'">
    <Reference Include="System.Collections.Immutable" HintPath="$(Bin64)\System.Collections.Immutable.dll" Private="False" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="Lib.Harmony" Version="2.4.2" />
    <PackageReference Include="Gameloop.Vdf" Version="0.6.2" />
  </ItemGroup>
</Project>
