<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <Version>1.0.0</Version>
    <Product>Pulsar</Product>
    <Copyright>© 2026 SpaceGT</Copyright>
  </PropertyGroup>
  <PropertyGroup>
    <AssemblyName>Pulsar.Shared</AssemblyName>
    <RootNamespace>Pulsar.Shared</RootNamespace>
  </PropertyGroup>
  <PropertyGroup>
    <TargetFrameworks>net48;net10.0</TargetFrameworks>
    <Nullable>disable</Nullable>
    <LangVersion>latest</LangVersion>
  </PropertyGroup>
  <PropertyGroup>
    <!-- Ensure different SteamWorks versions don't overwrite. -->
    <SteamFlavour Condition="'$(Steamworks)' == '$(Bin64)'">Legacy</SteamFlavour>
    <SteamFlavour Condition="'$(Steamworks)' == '$(Game2)'">Modern</SteamFlavour>
    <SteamFlavour Condition="'$(TargetPlatform)' == 'Linux'">Linux</SteamFlavour>
    <OutputPath>bin/$(SteamFlavour)/$(Configuration)/</OutputPath>
    <IntermediateOutputPath>obj/$(SteamFlavour)/$(Configuration)/</IntermediateOutputPath>
  </PropertyGroup>
  <Target Name="Verify" BeforeTargets="PrepareForBuild">
    <Error Condition="'$(Steamworks)' == ''" Text="Specify Steamworks path!" />
    <Error Condition="!Exists('$(Steamworks)/Steamworks.NET.dll')" Text="Steamworks.NET.dll not found!" />
  </Target>
  <ItemGroup>
    <ProjectReference Include="../Protocol/Protocol.csproj" GlobalPropertiesToRemove="Steamworks" />
  </ItemGroup>
  <ItemGroup>
    <Reference Include="Steamworks.NET" HintPath="$(Steamworks)/Steamworks.NET.dll" Private="False" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="FuzzySharp" Version="2.0.2" />
    <PackageReference Include="Lib.Harmony" Version="2.4.2" />
    <PackageReference Include="Microsoft.Win32.Registry" Version="5.0.0" />
    <PackageReference Include="Mono.Cecil" Version="0.11.6" />
    <PackageReference Include="Newtonsoft.Json" Version="13.0.3" />
    <PackageReference Include="NLog" Version="6.0.3" />
    <PackageReference Include="NuGet.Resolver" Version="6.7.1" />
    <PackageReference Include="protobuf-net" Version="2.4.9" />
  </ItemGroup>
</Project>
